name: Run writer.py every 12 hours

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run writer.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: python python/writer.py
